// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://igpnepkrocfuynqitlkv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlncG5lcGtyb2NmdXlucWl0bGt2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTcyNTc1NDQsImV4cCI6MjA3MjgzMzU0NH0.x8uPofHDsT3t7RlzcunEBU0YI-33H7oti_BPKS_T6tQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});